func a() -> Never {
    fatalError("에러 확인") 
}

print(1)
a()
print(2)